### ISSUE TITLE
Gem crash when model name is "Equipment"

### ISSUE THREAD

**Issue by Draqun** [hashrocket/decent_exposure#119]
This is weird but when my model has name Equipment gem crash (rails also has problem with this word). Please check this situation.

**Comment by mattpolito** [comment]
Hello @Draqun, I appreciate you bringing this to our attention. If you are still experiencing this issue, can you provide a bit more context around the error/crash?

**Comment by Draqun** [comment]
Hi.

In free time I prepare an example application.

Best regards. Draqun
