### ISSUE TITLE
Ability to decorate resource for helpers

### ISSUE THREAD

**Issue by timurvafin** [hashrocket/decent_exposure#122]
I'm looking for a way to have different behavior for resource in the controller
and in the view.

For example for `post` exposure it will be available
* in controller as `ActiveModel` instance
* in view as `PostPresenter` instance

```ruby
# app/posts_controller.rb
class PostsController
  expose(:post, strategy: PresenterStrategy)

  def show
    post # => ActiveModel instance
  end
end

# app/strategies/presenter_strategy.rb
class PresenterStrategy
  def helper
    resource.decorate
  end
end

# app/views/posts/show.html.slim
= post.status_line # => PostPresenter instance 
``` 

It could be implemented if strategy will have interface to define custom method for helper, rather that use [`helper_method`](https://github.com/hashrocket/decent_exposure/blob/master/lib/decent_exposure/expose.rb#L56) for it.

```ruby
def define_exposure_methods(name, exposure)
  define_method(name) do
    return _resources[name] if _resources.has_key?(name)
    _resources[name] = exposure.call(self)
  end
  hide_action name

  define_method("#{name}=") do |value|
    _resources[name] = value
  end
  hide_action "#{name}="

  helper do
    define_method(name) do
      exposure.helper(self)
    end
  end
end
```

What do you think guys about that?

Thanks,
Timur

**Comment by timurvafin** [comment]
Looks like this https://github.com/netguru/decent_decoration doing what I looking for

**Comment by mattpolito** [comment]
I prefer to assign the decorated objects to the helper. For me, it is more declarative that way.

```ruby
expose(:things)

def index
  self.things = ThingDecorator.new(things)
end
```
