### ISSUE TITLE
Work along with FriendlyID5 out of the box

### ISSUE THREAD

**Issue by johannesluedke** [hashrocket/decent_exposure#128]
When using FriendlyID5 (without deprecated finders and their monkey-patching), for a slug stored in params[:id], at the moment it's necessary to use

    expose(:object) { params[:id] ? Model.friendly.find(params[:id]) : Model.new(model_params) }

which takes away a lot of the niceness of decent_exposure.
It would be nice if the `.friendly.find` style could be configured out of the box along the lines of 

     expose(:object, config: :friendly) 

or similar

**Comment by mattpolito** [comment]
Thanks @johannesluedke for your input. That seems like a pretty specific request but we will definitely consider this use case when defining our feature request for v3.0.

**Comment by johannesluedke** [comment]
To make it less specific - it would be nice to be able to set `.friendly.find` as the finder option like so

      expose(:article, finder: < .friendly.find > )

Currently a symbol is passed to the `finder` option and I am not sure how a chained method called can be mapped to a symbol properly - but this would solve as well and be less specific

**Comment by mattpolito** [comment]
we will definitely have that

**Comment by johannesluedke** [comment]
Cool :) 
Thanks for your contributions (y)
