### ISSUE TITLE
new vs build for associations

### ISSUE THREAD

**Issue by brendon** [hashrocket/decent_exposure#132]
I'm currently having a bit of a problem with a STI model.

I'm replacing existing working code to use `decent_exposure` and the only difference I can see in the code generated is that `decent_exposure` uses `new` instead of `build` to set up the new record from the parent association. I think this might be affecting how the STI code creates the object as now Rails is ignoring any validations on the STI's particular type model and is only running the validations on the parent model.

I was wondering what the reason was for using `new` instead of `build` in this case. Is it because `build` is sometimes unavailable?

I've really enjoyed implementing `decent_exposure` overall. It definitely clarifies the code and I can get rid of all those nasty before_actions!

**Comment by brendon** [comment]
Actually, it's related to assigning attributes separate from the initialisation of the object.

https://github.com/rails/rails/commit/89b5b31cc4f8407f648a2447665ef23f9024e8a5

In Rails 4, the change above will initialise the object as its correct subclass based on the params[:model][:type] passed in, but it has to be done when the object is initialised.

I'll try to make a replacement strategy for this issue. Is it worth looking at making initialisation and attribute assignment in one step for `decent_exposure` in general?

**Comment by brendon** [comment]
I've had a go at this modification: https://github.com/hashrocket/decent_exposure/pull/133

All tests pass (a couple had to be adjusted).

Let me know what you think.

**Comment by mattpolito** [comment]
Closing post as v3.0 is a different codebase

**Comment by brendon** [comment]
I notice `3.0` uses new (not build) but at least passes in the params directly rather than in a two-step process. Apparently modern Rails doesn't have a difference between the two: https://stackoverflow.com/a/40989480/129798

**Comment by mattpolito** [comment]
@brendon Are you having an issue then?

**Comment by brendon** [comment]
Sorry no, not that I can see. I was just posting that there in case anyone else found the issue.
