### ISSUE TITLE
DoSExposure

### ISSUE THREAD

**Issue by gtd** [hashrocket/decent_exposure#136]
Hello, my apologies in advance for the snarky title, it's just I'm a little stressed out as DecentExposure has brought down our site for the second time in a week due to a minor error affecting a tiny percentage of requests, but which are invisible to us because the exception reporting tries to inspect a wide scope and loading every object in the database.

The initial issue #127 was closed unceremoniously, and I'm wondering if the maintainers are willing to accept patches or is it a NOFIX or what?

**Comment by mattpolito** [comment]
@gtd short answer, yes we accept patches to decent exposure. 

We've seen hundreds of apps in production using DecentExposure and it seems like the team at MUBI is the first to experience this. If you can provide more context around how exposures are being used around where you're experiencing the error... that may help.

**Comment by gtd** [comment]
Can you reopen #127 as @andydust already provided a reduced example in a gist there which I believe adequately explains the problem.

**Comment by mattpolito** [comment]
@gtd I've reopened #127 and look forward to going over any pull requests you'd like to send through.
