### ISSUE TITLE
Work with Mailers

### ISSUE THREAD

**Issue by facingsouth** [hashrocket/decent_exposure#150]
Wouldn't it be nice if all the methods are also made available in the Mailer?

**Comment by dudo** [comment]
+1

**Comment by vnegrisolo** [comment]
We implemented a branch for that. So please point to this branch:

```ruby
gem 'decent_exposure', github: 'decent_exposure', branch: 'expose-to-mailers'
```

I tested in a dummy application and it seemed to works fine. Please test this and let us know, so we can release a new version.

By the way, the current version of `decent_exposure` uses a method like `#{expoded_thing}_params`, so you'll need to set in the mailer instance your params. Check this:

```ruby
class PostMailer < ApplicationMailer
  attr_accessor :post_id

  expose :posts, -> { Post.last 5 }
  expose(:post, id: -> { post_id })

  def best_posts_ever(post_id = nil)
    self.post_id = post_id
    @greeting = "Hi"

    mail to: "to@example.org"
  end
end
```

```html
<h1>Post#best_posts_ever</h1>

<p>
  <%= @greeting %>, find me in app/views/post_mailer/best_posts_ever.html.erb
  Single Post = <%= post.inspect %>
  Post List = <%= posts.map(&:inspect) %>
</p>
```

**Comment by dudo** [comment]
Fantastic! That was easy. Thanks!

**Comment by facingsouth** [comment]
Super! Thanks for your lightning fast response.
