### ISSUE TITLE
Unable to expose question-mark methods

### ISSUE THREAD

**Issue by nashbridges** [hashrocket/decent_exposure#157]
This is a regression of v. 3x

When exposing a

```ruby
expose(:valid?) { ... }
```

I got 

```
/home/ubuntu/hb/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/abstract_controller/helpers.rb:65:in `class_eval': /home/ubuntu/hb/vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.5.2/lib/abstract_controller/helpers.rb:66: syntax error, unexpected '?', expecting ';' or '\n' (SyntaxError)
            def valid?=(*args, &blk)               ...
                     ^
```

**Comment by nashbridges** [comment]
In v2 only getter methods were exposed in a view: https://github.com/hashrocket/decent_exposure/blob/v2.3.3/lib/decent_exposure/expose.rb#L50

In v3 both getter and setter methods are exposed: https://github.com/hashrocket/decent_exposure/blob/master/lib/decent_exposure/exposure.rb#L69

**Comment by dnagir** [comment]
Why do we need magic setter?

**Comment by mattpolito** [comment]
@dnagir Not sure I understand your question

**Comment by nashbridges** [comment]
@mattpolito I belive the question was "why do we need settter (helper) in *a view*"? Changing app state from a view is bad practice anyway.

**Comment by mattpolito** [comment]
@nashbridges you are correct, we should not have setters available to the view.

**Comment by vnegrisolo** [comment]
hey @nashbridges and @mattpolito I created a PR with the change discussed here. I agree that we should not use a setter.

**Comment by nashbridges** [comment]
@hashrocketeer, how about normalize ivar_name, so that it will return valid name, e.g.

```
"valid?" -> "valid_QUESTION_MARK_"
```

**Comment by vnegrisolo** [comment]
hey guys, we could normalize the instance variable but this would not solve the problem due to the controller setter.

```ruby
irb(main):005:0> def bird?=(b)
irb(main):006:1> b
irb(main):007:1> end
SyntaxError: (irb):5: syntax error, unexpected '?', expecting ';' or '\n'
def bird?=(b)
```

@nashbridges do you see any solution for that?

**Comment by nashbridges** [comment]
@vnegrisolo the problem is only with setting/getting ivar (i.e. Context related), because methods themselves are [defined via `define_method](https://github.com/hashrocket/decent_exposure/blob/master/lib/decent_exposure/attribute.rb#L44)`, which doesn't care about syntax error:

```ruby
irb(main):001:0> define_method "valid?=" do
irb(main):002:1* "hello"
irb(main):003:1> end
=> :"valid?="
irb(main):004:0> send("valid?=")
=> "hello"
```

Not to mention that in reality question mark controller setter wouldn't be called anyway even if it exists.

**Comment by vnegrisolo** [comment]
you are totally right, the problem is on the `instance variable`. Thanks!

**Comment by vnegrisolo** [comment]
@nashbridges I have some code ready with the suggested change.

**Comment by nashbridges** [comment]
@vnegrisolo thanks for working on this!
