### ISSUE TITLE
Accept Symbolized Param Keys

### ISSUE THREAD

**Issue by kalinchuk** [hashrocket/decent_exposure#158]
It looks like we can only use String keys for `params` in tests or else decent exposure will not see any symbolized keys and attempt to build the object instead of fetching it. I'm referring to `params_id_key_candidates` which only has string keys.

For example, I have an RSpec test which passes in `{ id: 1 }` as the `params` but decent exposure returns a new record instead. If I change it to `{ 'id' => 1 }`, decent exposure returns the persisted record.

Is this the expected behavior or should `params_id_key_candidates` also have symbolized keys?

**Comment by vnegrisolo** [comment]
hey @kalinchuk,

we are using a similar spec here: https://github.com/hashrocket/decent_exposure/blob/master/spec/integration_spec.rb#L12

We are using the **symbol** hash syntax in the test and it seems that rspec is converting to the **string** version for us.

What version of `rspec` are you using?

**Comment by kalinchuk** [comment]
@vnegrisolo  I think we're using `3.5.1`.

**Comment by vnegrisolo** [comment]
rspec version should not be the problem so.
Well, Rails ActionController::Parameters will handle both string and symbol for us. The method that uses `params_id_key_candidates` was considering that, so it was an expected behavior for us.
Can you share your test? You might be stubbing `params` directly, and in this case you have to use the string version of that.

**Comment by kalinchuk** [comment]
@vnegrisolo Yes, I was stubbing `params` directly. It used to work with the old version of `decent_exposure` though.

**Comment by vnegrisolo** [comment]
ok. I don't think that we should change the current behavior in this case.

Maybe you should change your test to use a string key, or use `ActionController::Parameters` instead of a Hash. Either should work

Closing this issue for now. Thanks!
