### ISSUE TITLE
tag model

### ISSUE THREAD

**Issue by mzaragoza** [hashrocket/decent_exposure#161]
I have a model name tag. I notice that this is causing many problems 

  expose(:tags){ Tag.all.order('ID DESC') }
  expose(:tag, attributes: :tag_params)

is tag a reserve keyword?

**Comment by mattpolito** [comment]
What kind of problems are you experiencing?

**Comment by vnegrisolo** [comment]
I don't think that `tag` is a reserved word for decent_exposure. It's possibly `:attributes` option.

hey @mzaragoza did you check this wiki?: https://github.com/hashrocket/decent_exposure/wiki/Api-changes-in-version-3

If you have a problem to upgrade and this it's not listed there yet it would be nice if we add it there. Let us know.
