### ISSUE TITLE
Migration docs: automatic scoping.

### ISSUE THREAD

**Issue by dziulius** [hashrocket/decent_exposure#172]
2.x version had [automatic singular resource scoping](https://github.com/hashrocket/decent_exposure/tree/v2.3.3#scoping-your-object-queries), but migration docs fail to mention that such feature in v3.x does not exist anymore.

Without proper migration this could cause serious security issues.  It would be great to mention such changes in migration docs.

**Comment by mattpolito** [comment]
Info added to wiki entry for [api changes](https://github.com/hashrocket/decent_exposure/wiki/Api-changes-in-version-3)
