### ISSUE TITLE
What is the current level of activity here?

### ISSUE THREAD

**Issue by hazah** [hashrocket/decent_exposure#176]

**Comment by mattpolito** [comment]
@hazah How much activity are you looking for?

**Comment by hazah** [comment]
I have a pull request that solves a particular issue that I want to see implemented if it makes sense, @mattpolito. Seems like a level that accepts pull requests (or reviews them) would be quite sufficient for the common cause.

**Comment by m5rk** [comment]
I stumbled upon this issue. @hazah I assume you mean #164? As a casual observer, what I notice is that your PR has no description and no tests, which means the reviewer has to infer the intent and the pros and cons. Perhaps you could help by making those things explicit?

**Comment by hazah** [comment]
So I guess no review for the actual pull request?
