### ISSUE TITLE
Which is preferred a block or a lambda-argument?

### ISSUE THREAD

**Issue by wenga86** [hashrocket/decent_exposure#177]
I see you can pass in a custom fetch as either a block or a lambda-argument, but which is preferred? Are there pros and cons to both? Under the hood they seem to do almost the same thing. Just trying to understand.

**Comment by mattpolito** [comment]
@wenga86 I guess it depends on what you're doing. If you are dealing with a singular and want to redefine the fetch, i'd use a lambda and pass it to fetch:

```ruby
expose(:thing, fetch: -> { some_other_fetch_logic })
```

However if you were fetching a collection, I would use a block ( which overrides any argument you'd pass anyway ):

```ruby
expose(:collection_of_things) { Thing.all }
```

Hope that clears things up for you and is what you're looking for.
