### ISSUE TITLE
out of scope

### ISSUE THREAD

**Issue by mzaragoza** [hashrocket/decent_exposure#179]
I was under the precision that in this example  `post` was a find in `posts`  and not a find in Post.all 

am I correct? 

```
  expose(:posts, -> { Post.last(10) })
  expose(:post)
```

I was working in one of my applicatins where now I can just pass in any post id and its found 

I can make it where its 

`  expose(:post, -> Post.last(10).find(params[:id]))` 
but I dont think that is what it was intended

**Comment by mattpolito** [comment]
@mzaragoza This was a significant change in version 3. The singular exposures have no relationship to the plural anymore.

**Comment by mzaragoza** [comment]
Well that is good to know

**Comment by mzaragoza** [comment]
do you know how to do 

  `expose(: post, attributes: : post_params)`

but to also include `expose(:post, -> Post.last(10).find(params[:id]))`

**Comment by mattpolito** [comment]
@mzaragoza try:

```ruby
expose(:post, scope: -> { Post.last(10) })
```
