### ISSUE TITLE
expose(:tag) { ... } breaks ActionView

### ISSUE THREAD

**Issue by jessedoyle** [hashrocket/decent_exposure#180]
This may not be a fault in `DecentExposure`, but we recently encountered a hard-to-debug issue when using this gem. Here's the scenario:

#### Controller
```ruby
class MyController < ApplicationController
  expose(:tag) { Tag.find_by(name: 'test') }
  expose(:example) { Example.new(tag: tag) }

  def new; end
end
```

#### View
```erb
<%= form_for example do |f| %>
  <%= f.input :data %>
  <%= f.submit %>
<% end %>
```

Suddenly, we were seeing an `ArgumentError` when rendering the form:

```
ArgumentError - wrong number of arguments (given 2, expected 0)
```

What wasn't immediately obvious was that we accidentally overwrote the `tag` method `ActionView` uses within the context of the view.

Again, I don't think this is necessary a fault with DecentExposure, maybe some documentation would help future users with a similar issue? 

A more dramatic approach would be to check if the `expose(:something) {}` call will overwrite any methods in the view and raise a meaningful exception.

Feel free to close this issue if you think it's not a concern! I was just hoping to provide some information to those who may encounter a similar issue.

**Comment by mattpolito** [comment]
@jessedoyle Thanks for bringing this up. You are correct in that it is not an actual issue with DecentExposure but I see where it could confuse. 

An exposure is creating a method in your controller and making that method a helper in your view. It just happens that it overwrote a helper already in play via ActionView. Not sure what we can easily do about it off the top of my head as the exposures are used in different contexts but thanks for bringing this up. Also, if you figure something out to help alleviate the potential pain for others... I'd gladly take a look at a PR.

Thanks again!

**Comment by vinc** [comment]
Just got the same problem and it took me a while to figure out the cause. A check before defining the helper and a meaningful exception would indeed be helpful.

**Comment by vinc** [comment]
@mattpolito I'm writing a small PR regarding this issue but it'll need some improvements I think.
