### ISSUE TITLE
Exposed things show up in the `action_methods` list

### ISSUE THREAD

**Issue by crawfoal** [hashrocket/decent_exposure#182]
The [documentation](https://apidock.com/rails/AbstractController/Base/action_methods/class) for `AbstractController::Base#action_methods` says that it is a "list of method names that should be considered actions" and that [`#hidden_actions`](https://apidock.com/rails/AbstractController/Base/hidden_actions/class) can be used to remove methods that shouldn't be considered actions.

Concrete example:
```ruby
class PrizesController < ApplicationController
  expose :prize

  def new; end

  def create
    if prize.save
      redirect_to admin_dashboards_show_path, notice: t('.success')
    else
      render 'new'
    end
  end

  ...
end
```

```
[2] pry(main)> PrizesController.action_methods
=> #<Set: {"new", "create", "prize", "prize="}>
```

If you guys will have time to review a PR for this, I can start working on it. Just let me know 🙂  I'm thinking about applying to work with your company and this would be a good chance to get to know each other.

**Comment by mattpolito** [comment]
@crawfoal Thanks for bringing this up. We removed this feature of DecentExposure a while ago as `hidden_actions` was removed from Rails. However, if you find a better way to handle this scenario, I'd be happy to look over a PR.

Thanks for your input.

**Comment by crawfoal** [comment]
Oh shoot, I keep accidentally looking at old docs.

The only idea I have right now feels kinda messy... we could register exposure methods as they're defined and then wrap Rails's `action_methods` and filter registered methods out of the set they return. I guess maybe it's not all that messy, but I've looked at my use case again and it's actually not essential to remove the exposure methods, so I don't care as much now. If someone else has a good reason to address this or it's important to you guys, I'm happy to work with you guys to find a solution.

**Comment by brendon** [comment]
From what I could tell, at the Rails end, they no longer care about the whole action_methods setup as the router now defines what an action is rather than the controller.
