### ISSUE TITLE
Preferred mechanism for overriding an exposure

### ISSUE THREAD

**Issue by brendon** [hashrocket/decent_exposure#184]
Say if I want to paginate an exposed association in the controller method only if the request is for `html`, how would I go about doing that. Trying re-assign just creates a local variable. Do I have to dig down to the hidden instance variable and change that?

I remember there used to be a mechanism for overriding in the older `decent_exposure` but can't find any mention of it here.

**Comment by mattpolito** [comment]
Without more context about the code and what you're trying to do I don't know if I can say for sure.

However, DecentExposure is really only creating a method as a finder and a helper method for the view. You could just redefine it in the action:

```ruby
self.thing = thing.paginate
```

**Comment by brendon** [comment]
Ah I see, so accessing it through `self` is the way to modify it :) Thanks for that.

In the end I actually created another exposure `paginated_thing` that did the pagination, that way I could grab whatever one I wanted from the particular view.

Thanks again for your help :)
