### ISSUE TITLE
Ruby 3.0 support?

### ISSUE THREAD

**Issue by mensfeld** [hashrocket/decent_exposure#196]
Hey, is there anything blocking bumping this? https://github.com/hashrocket/decent_exposure/blob/master/decent_exposure.gemspec#L23 - happy to do the PR, just asking in advance.

**Comment by mattpolito** [comment]
Nothing specific blocking, just haven't looked into it yet.

**Comment by pat** [comment]
Just put together a PR (#197) - the hard work was already done in #195 though!

**Comment by mattpolito** [comment]
This should be all taken care of now with the new gem release. Thank you for pointing it out @mensfeld & @pat.

**Comment by mensfeld** [comment]
@mattpolito thank you :pray:
