### ISSUE TITLE
Draper strategy not working with nested resources (has_one association)

### ISSUE THREAD

**Issue by JeanMertz** [hashrocket/decent_exposure#98]
Using: https://github.com/voxdolo/decent_exposure/wiki/Strategies:-Draper-(Decorator)-implementation

```ruby
class ShiftPartialsController < ApplicationController
  expose(:shift)
  expose(:shift_partial, ancestor: :shift)

  def create
  end
end
```

when `create` is fired, the following error is returned:

```
NoMethodError: undefined method `new' for #<ShiftPartialDecorator:0x007f882939fb08>
```

This is because (apparently) the `new` method is not delegated from ShiftPartialDecorator to ShiftPartial (even though I've set `delegate_all` in the decorator).

The solution would be to use `shift.build_shift_partial` instead of `shift.new`, but I'm not sure how to implement it the correct way in the strategy.

Is this a known issue? Any other ways to solve this? What's the reasoning behind using `new` instead of the `build` methods provided by Rails?

**Comment by corroded** [comment]
@mattpolito i noticed this was closed. Is this fixed in the newest release?

**Comment by mattpolito** [comment]
@corroded We're working on a new version that will handle this a bit differently.

**Comment by corroded** [comment]
Sweet. Thanks!

**Comment by brendon** [comment]
Just wondering if this was ever handled?

**Comment by mattpolito** [comment]
@brendon This should no longer be an issue in versions greater than 3. Decorators are handled differently now.

**Comment by brendon** [comment]
Ah sorry, I got the wrong issue :) It was https://github.com/hashrocket/decent_exposure/issues/132 that I wanted to ping :)
